# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  system.stateVersion = "25.11";
  networking.hostName = "pc-matt-nix-vm";
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  virtualisation.vmware.guest.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1153cd46-0b8c-4017-8383-fd99132dd4f5";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C886-7B81";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/775d86e7-3e78-4a20-896b-44ff838e8170"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
